FORMAT: 1A
HOST: http://easyapply.online/api/

# easy-apply

Easy Apply is a cloud based school admission processing service.

## City [/cities]

### List all cities [GET]

+ Response 200 (application/json)

        [
            "city-1",
            "city-2"
            "city-3",
        ]

## Locality [/cities/{city_name}/localities]

+ Parameters
    + city_name (string) - name of the city

### List all localities in a city [GET]

+ Response 200 (application/json)

        [
            "locality-1",
            "locality-2",
            "locality-3"
        ]

## Schools [/cities/{city_name}/localities/{locality_name}/schools]

+ Parameters
    + city_name (string) - name of the city
    + locality_name (string) - name of the locality

### Get all schools' details in a locality of a city [GET]

+ Response 200 (application/json)

        [
            {
                id: 1,
                name: "school-1",
                description: "desc-1",
                locality : "Indiranagar",
                city : "Bangalore",
                country : "India",
                address : "Somewhere",
                phone : "2323232",
                board : "CBSE",
                established : "1983",
                url : "http://xyz.com",
                admissions_for : [ "Montessorie", "Nursery"]
            },
            {
                id: 1,
                name: "school-2",
                description: "desc-2",
                locality : "Indiranagar",
                city : "Bangalore",
                country : "India",
                address : "Somewhere",
                phone : "2323232",
                board : "CBSE",
                established : "1983",
                url : "http://xyz.com",
                admissions_for : [ "Montessorie"]
            }
        ]

## School [/schools/{school_id}]

+ Parameters
    + school_id (number) - ID of the school in the form of an integer

### Get details of a school [GET]

+ Response 200 (application/json)

        {
            id: 1,
            name: "school-1",
            description: "desc-1",
            locality : "Indiranagar",
            city : "Bangalore",
            country : "India",
            address : "Somewhere",
            phone : "2323232",
            board : "CBSE",
            established : "1983",
            url : "http://xyz.com",
            admissions_for : [ "Montessorie", "Nursery"]
        }
    
## Validate Google Sign-in [/validate]

### Validate logon user after successful sign-in [POST]

+ Request (application/json)

        {
            id_token="extract from Google auth API"
        }
        
+ Response 200 (application/json)

        {
            status: 'ok'
        }

## Profile [/users/{user_id}]

+ Parameters
    + user_id (number) - ID of the user

### Get user profile details [GET]

+ Response 200 (application/json)

        {
            first_name : "Raja",
            last_name : "Vengala",
            country : "India",
            city : "Bangalore",
            dob : "06-Jul-1981",
            email : "raj.vengala@outlook.com",
            phone : "+919972095475"
        }

### Update user profile [PATCH]

User should update city and phone number after creating profile.

+ Request (application/json)

        {
            user_id: 'asdasd',
            city: 'Bangalore',
            phone: 'asdasd'
        }

+ Response 204

## User's Application Data [/users/{user_id}/app_data]

+ Parameters
    + user_id (number) - ID of the user in the form of an integer

### Get user's application data [GET]

+ Response 200 (application/json)

        {
            "home_address" : "Somewhere",
            "home_phone" : "080-25282673",
            "religion" : "None",
            "nationality" : "Indian"
            "father" : {
                "first_name" : "Raja",
                "last_name" : "Vengala",
                "dob" : "06/07/1981",
                "salary" : "10000 per annum",
                "company" : "Oracle",
                "work_address" : "somewhere",
                "work_phone" : "Something",
                "designation" : "Something",
                "mobile" : "9972095475",
                "email" : "raj.vengala@outlook.com"
            },
            "mother" : {
                "firs_name" : "Pallavi",
                "last_name" : "Venugopal",
                "dob" : "09/10/1981",
                "salary" : "20000 per annum",
                "company" : "IFlex",
                "work_address" : "somewhere",
                "work_phone" : "something",
                "designation" : "Something",
                "mobile" : "9880055475",
                "email" : "pallavi.vreddy@gmail.com"
            },
            "applicants" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }

### Create user's application data [POST]

+ Request (application/json)

        {
            "home_address" : "Somewhere",
            "home_phone" : "080-25282673",
            "religion" : "None",
            "nationality" : "Indian"
            "father" : {
                "first_name" : "Raja",
                "last_name" : "Vengala",
                "dob" : "06/07/1981",
                "salary" : "10000 per annum",
                "company" : "Oracle",
                "work_address" : "somewhere",
                "work_phone" : "Something",
                "designation" : "Something",
                "mobile" : "9972095475",
                "email" : "raj.vengala@outlook.com"
            },
            "mother" : {
                "first_name" : "Pallavi",
                "last_name" : "Venugopal",
                "dob" : "09/10/1981",
                "salary" : "20000 per annum",
                "company" : "IFlex",
                "work_address" : "somewhere",
                "work_phone" : "something",
                "designation" : "Something",
                "mobile" : "9880055475",
                "email" : "pallavi.vreddy@gmail.com"
            },
            "kids" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }
        
+ Response 200 (application/json)

### Update user's application data [PATCH]

Update all/some of the properties of application data object

+ Request (application/json)

        {
            user_id: 'asdasd',
            home_phone: '99812323',
            "applicants" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }

+ Response 204

## User's Applications [/users/{user_id}/applications]

+ Parameters
    + user_id (number) - ID of the user in the form of an integer

### Get user's school applications [GET]

+ Response 200 (application/json)

        [
            {
                "_id" : ObjectId("599e9b45db3e672960d64d77"),
                "school" : {
                    "_id" : ObjectId("599e8ffedb3e672960d64d75"),
                    "name" : "National Public School",
                    "description" : "tasdasdasd",
                    "locality" : "Indiranagar",
                    "city" : "Bangalore",
                    "country" : "India",
                    "address" : "Somewhere",
                    "phone" : "2323232",
                    "board" : "CBSE",
                    "established" : "1983",
                    "url" : "http://xyz.com",
                    "grades" : [ 
                        "Montessorie", 
                        "Nursery"
                    ]
    
                },
                "user_id" : "unique_google_id",
                "admission_year" : "2018",
                "applicant" : "Keara Vengala",
                "grade" : "nursery",
                "status" : "Paid",
                "amount" : "530",
                "payment_ref" : "asdasdasdasd"
            }
        ]


## Submit Application [/applications]

### Submit application for a school [POST]

+ Request (application/json)

        {
            "user_id" : "unique_google_id",
            "school_id": "xxxxx",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "amount" : "530",
        }
        
+ Response 200 (application/json)

        {
            "_id" : ObjectId("599e9b45db3e672960d64d77"),
            "school" : {
                "_id" : ObjectId("599e8ffedb3e672960d64d75"),
                "name" : "National Public School",
                "description" : "tasdasdasd",
                "locality" : "Indiranagar",
                "city" : "Bangalore",
                "country" : "India",
                "address" : "Somewhere",
                "phone" : "2323232",
                "board" : "CBSE",
                "established" : "1983",
                "url" : "http://xyz.com",
                "admissions_for" : [ 
                    "Montessorie", 
                    "Nursery"
                ]
            },
            "user_id" : "rvengala81@gmail.com",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "status" : "Paid",
            "amount" : "530",
            "payment_ref" : "asdasdasdasd"
        }

## Schools' applications [/schools/{school_id}/applications]

+ Parameters
    + school_id (number) - ID of the school in the form of an integer
    
### Get all applications for a school [GET]

+ Response 200 (application/json)

        {
            "_id" : ObjectId("599e9b45db3e672960d64d77"),
            "school" : ObjectId("599e9b45db3e672960d64d77"),
            "user_id" : "unique_google_id",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "status" : "Paid",
            "amount" : "530",
            "payment_ref" : "asdasdasdasd"
        }
        
## Payment Status [/payment{?payment_id,payment_request_id}]

+ Parameters
    + payment_id (optional) - Instamojo payyment id
    + payment_request_id (optional) - Instamojo payyment request id
    
### Get the status of application payment [GET]

+ Response 200 (application/json)

        {
            "payment_request": {
                "id": "d66cb29dd059482e8072999f995c4eef",
                "phone": "+919999999999",
                "email": "foo@example.com",
                "buyer_name": "John Doe",
                "amount": "2500.00",
                "purpose": "FIFA 16",
                "status": "Sent",
                "send_sms": true,
                "send_email": true,
                "sms_status": "Pending",
                "email_status": "Sent",
                "shorturl": "https://imjo.in/NNxHg",
                "longurl": "https://www.instamojo.com/@ashwini/d66cb29dd059482e8072999f995c4eef",
                "redirect_url": "http://www.example.com/redirect/",
                "webhook": "http://www.example.com/webhook/",
                "payments": [
                     {
                        "payment_id": "MOJO7328005J91064462", 
                        "quantity": 1, 
                        "status": "Credit", 
                        "link_slug": null, 
                        "link_title": null, 
                        "buyer_name": "Buyer Name", 
                        "buyer_phone": "9901000000", 
                        "buyer_email": "buyer@instamojo.com", 
                        "currency": "INR", 
                        "unit_price": "100.00", 
                        "amount": "100.00", 
                        "fees": "5.00", 
                        "shipping_address": null, 
                        "shipping_city": null, 
                        "shipping_state": null, 
                        "shipping_zip": null, 
                        "shipping_country": null, 
                        "discount_code": null, 
                        "discount_amount_off": null, 
                        "variants": [], 
                        "custom_fields": {}, 
                        "affiliate_id": null, 
                        "affiliate_commission": "0", 
                        "created_at": "2017-03-28T13:57:21.229398Z", 
                        "payment_request": "https://instamojo.com/api/1.1/payment-requests/be65d8abecc549918e8d8e61c801ae6f/"
                    }
                ],
                "created_at": "2015-10-07T21:36:34.665Z",
                "modified_at": "2015-10-07T21:36:37.572Z",
                "allow_repeated_payments": false
            },
            "success": true
        }

## Payment Status Hook [/payment]

### Receive the status of application payment [POST]

+ Request (application/x-www-form-urlencoded)

        inkrefer_to_the_link=https://docs.instamojo.com/docs/payments-api

+ Response 200 (text/plain-text)