FORMAT: 1A
HOST: http://easyapply.online/api/

# easy-apply

Easy Apply is a cloud based school admission processing service.

## City [/cities]

### List all cities [GET]

+ Response 200 (application/json)

        [
            "city-1",
            "city-2"
            "city-3",
        ]

## Locality [/cities/{city_name}/localities]

+ Parameters
    + city_name (string) - name of the city

### List all localities in a city [GET]

+ Response 200 (application/json)

        [
            "locality-1",
            "locality-2",
            "locality-3"
        ]

## Schools [/cities/{city_name}/localities/{locality_name}/schools]

+ Parameters
    + city_name (string) - name of the city
    + locality_name (string) - name of the locality

### Get all schools' details in a locality of a city [GET]

+ Response 200 (application/json)

        [
            {
                id: 1,
                name: "school-1",
                description: "desc-1",
                locality : "Indiranagar",
                city : "Bangalore",
                country : "India",
                address : "Somewhere",
                phone : "2323232",
                board : "CBSE",
                established : "1983",
                url : "http://xyz.com",
                admissions_for : [ "Montessorie", "Nursery"]
            },
            {
                id: 1,
                name: "school-2",
                description: "desc-2",
                locality : "Indiranagar",
                city : "Bangalore",
                country : "India",
                address : "Somewhere",
                phone : "2323232",
                board : "CBSE",
                established : "1983",
                url : "http://xyz.com",
                admissions_for : [ "Montessorie"]
            }
        ]

## School [/schools/{school_id}]

+ Parameters
    + school_id (number) - ID of the school in the form of an integer

### Get details of a school [GET]

+ Response 200 (application/json)

        {
            id: 1,
            name: "school-1",
            description: "desc-1",
            locality : "Indiranagar",
            city : "Bangalore",
            country : "India",
            address : "Somewhere",
            phone : "2323232",
            board : "CBSE",
            established : "1983",
            url : "http://xyz.com",
            admissions_for : [ "Montessorie", "Nursery"]
        }
    
## Validate Google Sign-in [/validate]

### Validate logon user after successful sign-in [POST]

+ Request (application/json)

        {
            id_token="extract from Google auth API"
        }
        
+ Response 200 (application/json)

        {
            status: 'ok'
        }

## Profile [/users/{user_id}]

+ Parameters
    + user_id (number) - ID of the user

### Get user profile details [GET]

+ Response 200 (application/json)

        {
            first_name : "Raja",
            last_name : "Vengala",
            country : "India",
            city : "Bangalore",
            dob : "06-Jul-1981",
            email : "raj.vengala@outlook.com",
            phone : "+919972095475"
        }

### Update user profile [PATCH]

User should update city and phone number after creating profile.

+ Request (application/json)

        {
            user_id: 'asdasd',
            city: 'Bangalore',
            phone: 'asdasd'
        }

+ Response 204

## User's Application Data [/users/{user_id}/app_data]

+ Parameters
    + user_id (number) - ID of the user in the form of an integer

### Get user's application data [GET]

+ Response 200 (application/json)

        {
            "home_address" : "Somewhere",
            "home_phone" : "080-25282673",
            "religion" : "None",
            "nationality" : "Indian"
            "father" : {
                "first_name" : "Raja",
                "last_name" : "Vengala",
                "dob" : "06/07/1981",
                "salary" : "10000 per annum",
                "company" : "Oracle",
                "work_address" : "somewhere",
                "work_phone" : "Something",
                "designation" : "Something",
                "mobile" : "9972095475",
                "email" : "raj.vengala@outlook.com"
            },
            "mother" : {
                "firs_name" : "Pallavi",
                "last_name" : "Venugopal",
                "dob" : "09/10/1981",
                "salary" : "20000 per annum",
                "company" : "IFlex",
                "work_address" : "somewhere",
                "work_phone" : "something",
                "designation" : "Something",
                "mobile" : "9880055475",
                "email" : "pallavi.vreddy@gmail.com"
            },
            "applicants" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }

### Create user's application data [POST]

+ Request (application/json)

        {
            "home_address" : "Somewhere",
            "home_phone" : "080-25282673",
            "religion" : "None",
            "nationality" : "Indian"
            "father" : {
                "first_name" : "Raja",
                "last_name" : "Vengala",
                "dob" : "06/07/1981",
                "salary" : "10000 per annum",
                "company" : "Oracle",
                "work_address" : "somewhere",
                "work_phone" : "Something",
                "designation" : "Something",
                "mobile" : "9972095475",
                "email" : "raj.vengala@outlook.com"
            },
            "mother" : {
                "first_name" : "Pallavi",
                "last_name" : "Venugopal",
                "dob" : "09/10/1981",
                "salary" : "20000 per annum",
                "company" : "IFlex",
                "work_address" : "somewhere",
                "work_phone" : "something",
                "designation" : "Something",
                "mobile" : "9880055475",
                "email" : "pallavi.vreddy@gmail.com"
            },
            "kids" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }
        
+ Response 200 (application/json)

### Update user's application data [PATCH]

Update all/some of the properties of application data object

+ Request (application/json)

        {
            user_id: 'asdasd',
            home_phone: '99812323',
            "applicants" : [ 
                {
                    "first_name" : "Keara",
                    "last_name" : "Vengala",
                    "sex" : "Female",
                    "dob" : "07-Dec-2011",
                    "aadhar_id" : "232ASD",
                    "physical_disability" : "some comments",
                    "mental_disability" : "some comments"
                }
            ]
        }

+ Response 204

## User's Applications [/users/{user_id}/applications]

+ Parameters
    + user_id (number) - ID of the user in the form of an integer

### Get user's school applications [GET]

+ Response 200 (application/json)

        [
            {
                "_id" : ObjectId("599e9b45db3e672960d64d77"),
                "school" : {
                    "_id" : ObjectId("599e8ffedb3e672960d64d75"),
                    "name" : "National Public School",
                    "description" : "tasdasdasd",
                    "locality" : "Indiranagar",
                    "city" : "Bangalore",
                    "country" : "India",
                    "address" : "Somewhere",
                    "phone" : "2323232",
                    "board" : "CBSE",
                    "established" : "1983",
                    "url" : "http://xyz.com",
                    "grades" : [ 
                        "Montessorie", 
                        "Nursery"
                    ]
    
                },
                "user_id" : "unique_google_id",
                "admission_year" : "2018",
                "applicant" : "Keara Vengala",
                "grade" : "nursery",
                "status" : "Paid",
                "amount" : "530",
                "payment_ref" : "asdasdasdasd"
            }
        ]


## Submit Application [/applications]

### Submit application for a school [POST]

+ Request (application/json)

        {
            "user_id" : "unique_google_id",
            "school_id": "xxxxx",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "amount" : "530",
        }
        
+ Response 200 (application/json)

        {
            "_id" : ObjectId("599e9b45db3e672960d64d77"),
            "school" : {
                "_id" : ObjectId("599e8ffedb3e672960d64d75"),
                "name" : "National Public School",
                "description" : "tasdasdasd",
                "locality" : "Indiranagar",
                "city" : "Bangalore",
                "country" : "India",
                "address" : "Somewhere",
                "phone" : "2323232",
                "board" : "CBSE",
                "established" : "1983",
                "url" : "http://xyz.com",
                "admissions_for" : [ 
                    "Montessorie", 
                    "Nursery"
                ]
            },
            "user_id" : "rvengala81@gmail.com",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "status" : "Paid",
            "amount" : "530",
            "payment_ref" : "asdasdasdasd"
        }

## Schools' applications [/schools/{school_id}/applications]

+ Parameters
    + school_id (number) - ID of the school in the form of an integer
    
### Get all applications for a school [GET]

+ Response 200 (application/json)

        {
            "_id" : ObjectId("599e9b45db3e672960d64d77"),
            "school" : ObjectId("599e9b45db3e672960d64d77"),
            "user_id" : "unique_google_id",
            "admission_year" : "2018",
            "applicant" : "Keara Vengala",
            "grade" : "nursery",
            "status" : "Paid",
            "amount" : "530",
            "payment_ref" : "asdasdasdasd"
        }